name: app_environment
channels:
  - snowflake
dependencies:
  - hf-xet=1.1.8
  - langchain=0.3.27
  - langchain-community=0.3.30
  - opentelemetry-instrumentation-chromadb=0.47.2
  - sentence-transformers=4.1.0
  - snowflake-snowpark-python
