name: app_environment
channels:
  - snowflake
dependencies:
  - hf-xet=1.1.8
  - langchain=1.0.0
  - langchain-community=0.4
  - langchain-core=1.0.0
  - langchain-text-splitters=1.0.0
  - sentence-transformers=4.1.0
  - snowflake-snowpark-python
